version: "3"

services:
  api-app:
    image: bigelio/api-app:latest
    restart: unless-stopped
    networks:
      - app-network

  web-app:
    image: bigelio/web-app:latest
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
